using System;
using System.Collections.Generic;

namespace Assignment.Core
{
    public class ApiHome
    {
        public string Message { get; set; }
        public int HomeId { get; set; }
        public int ListingId { get; set; }
        public string ListingTitle { get; set; }
        public string ListingNumber { get; set; }
        public bool isSpec { get; set; }
        public int PlanId { get; set; }
        public string PlanName { get; set; }
        public string SpecNum { get; set; }
        public int IsDescAutoGenerated { get; set; }
        public string MoveInData { get; set; }
        public string MarketingDesc { get; set; }
        public string Addr { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public int? Br { get; set; }
        public int? BrLo { get; set; }
        public int? BrHi { get; set; }
        public int MasterBedroomLocation { get; set; }
        public int? Ba { get; set; }
        public int? BaLo { get; set; }
        public int? BaHi { get; set; }
        public bool DisplayAddress { get; set; }
        public int FeedProviderId { get; set; }
        public int? HBa { get; set; }
        public int? HBaLo { get; set; }
        public int? HBaHi { get; set; }
        public float? St { get; set; }
        public float? StLo { get; set; }
        public float? StHi { get; set; }
        public float? Gr { get; set; }
        public float? GrLo { get; set; }
        public float? GrHi { get; set; }
        public int? Sft { get; set; }
        public int? SftLo { get; set; }
        public int? SftHi { get; set; }
        public int LotSft { get; set; }
        public string LotNumber { get; set; }
        public float Price { get; set; }
        public float PriceLo { get; set; }
        public float PriceHi { get; set; }
        public float ModelPrice { get; set; }
        public string ProviderUrl { get; set; }
        public int NumLivingAreas { get; set; }
        public string Status { get; set; }
        public int isHotHome { get; set; }
        public string thumb { get; set; }
        public string Phone { get; set; }
        public string PhoneTracking { get; set; }
        public bool isTrackingNumber { get; set; }
        public int MktId { get; set; }
        public string MarketName { get; set; }
        public string MarketStateAbbr { get; set; }
        public string MarketStateName { get; set; }
        public string MlsNumber { get; set; }
        public int MlsProviderId { get; set; }
        public int CommId { get; set; }
        public string CommName { get; set; }
        public int ParentCommId { get; set; }
        public string ParentCommName { get; set; }
        public bool isParentCommActive { get; set; }
        public string CommListingTypeFlag { get; set; }
        public string CommType { get; set; }
        public string CommProjectType { get; set; }
        public string CommDesc { get; set; }
        public string CommUrl { get; set; }
        public string CommAddr { get; set; }
        public string CommAddr2 { get; set; }
        public string CommCity { get; set; }
        public string CommState { get; set; }
        public string CommZip { get; set; }
        public float CommLat { get; set; }
        public float CommLng { get; set; }
        public string CommBannerImage { get; set; }
        public float CommPriceLow { get; set; }
        public float CommPriceHigh { get; set; }
        public bool IsBasic { get; set; }
        public string SchoolDistricts { get; set; }
        public float Lat { get; set; }
        public float Lng { get; set; }
        public string PlanTypeId { get; set; }
        public string PlanBrandName { get; set; }
        public string PlanBrandLogo { get; set; }
        public ApiBuilder Builder { get; set; }
        public ApiBrand Brand { get; set; }
        public string PlanViewerUrl { get; set; }
        public string TourUrl { get; set; }
        public string Time { get; set; }
        public string EnvisionUrl { get; set; }
        public List<ApiImage> Images { get; set; }
        public List<ApiImage> PlanImages { get; set; }
        public string VideoUrl { get; set; }
        public List<ApiVideo> Videos { get; set; }
        public List<ApiSummary> Summaries { get; set; }
        public List<ApiSummary> PlanAmenities { get; set; }
        public List<ApiSummary> LivingAreas { get; set; }
        public List<ApiInteractiveMedia> IntMedia { get; set; }
        public List<ApiCustomAmenity> CustomAmenities { get; set; }
        public List<ApiHomeOption> HomeOptions { get; set; }
        // public List<ApiSchoolDistrict> Schools { get; set; }
        // public List<ApiAmenity> Amenities { get; set; }
        // public List<ApiUtility> Utilities { get; set; }
        public bool IsActive { get; set; }
        public string SalesOffAddr { get; set; }
        public string SalesOffAddr2 { get; set; }
        public string SalesOffCity { get; set; }
        public string SalesOffZipCode { get; set; }
        public string SalesOffState { get; set; }
        public string SalesOffEmail { get; set; }
        public string SpecType { get; set; }
        public float SoldPrice { get; set; }
        public DateTime SoldDate { get; set; }
        public string CommStateAbbr { get; set; }
        public string Hours { get; set; }
        public string DrivingDirections { get; set; }
        public string Map { get; set; }
        public DateTime LastModified { get; set; }
        public string CommunityMap { get; set; }
        public string SpecSaleStatus { get; set; }
        // public List<ApiSalesAgent> Agents { get; set; }
        public float AgentCommision { get; set; }
        public int Adult { get; set; }
        public int AgeRestricted { get; set; }
        public int GreenProgram { get; set; }
        public string CorporationName { get; set; }
        public string PlanUrl { get; set; }
        public string SpecificationUrl { get; set; }
        public string FulfilmentCode { get; set; }
        public int PreferredScore { get; set; }
        // public List<ApiBrochure> Brochures { get; set; }
        // public List<BookmarkAttribute> Bookmarks { get; set; }
        public bool OutOfCommunityFlag { get; set; }
        public string Server { get; set; }
        // public List<ApiFeesAndRates> FeesAndRates { get; set; }
        public Exception Error { get; set; }
        public int OwnerPartner { get; set; }
        public string TranslationHomeId { get; set; }
        public string TranslationCommId { get; set; }
        // public List<ApiUrgencyResponse> UrgencyData { get; set; }
        public string BasicListingTypeCode { get; set; }
        // public List<IVerboseLogger> VerboseLogger { get; set; }
        public string WebBugUrl { get; set; }
        public string YearBuilt { get; set; }
        public int AgentId { get; set; }
        // public ApiAugmentedReality AugmentedRealityHomeViewer { get; set; }
        // public ApiAugmentedReality AugmentedRealityHomeOnLot { get; set; }

        public ApiHome()
        {
            Images = new List<ApiImage>();
            PlanImages = new List<ApiImage>();
            Videos = new List<ApiVideo>();
            Summaries = new List<ApiSummary>();
            PlanAmenities = new List<ApiSummary>();
            LivingAreas = new List<ApiSummary>();
            IntMedia = new List<ApiInteractiveMedia>();
            CustomAmenities = new List<ApiCustomAmenity>();
            HomeOptions = new List<ApiHomeOption>();
            // Schools = new List<ApiSchoolDistrict>();
            // Amenities = new List<ApiAmenity>();
            // Utilities = new List<ApiUtility>();
            // Agents = new List<ApiSalesAgent>();
            // Brochures = new List<ApiBrochure>();
            // Bookmarks = new List<BookmarkAttribute>();
            // FeesAndRates = new List<ApiFeesAndRates>();
            // UrgencyData = new List<ApiUrgencyResponse>();
            // VerboseLogger = new List<IVerboseLogger>();
        }
    }
}